name: Run PHPUnit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install dependencies
      run: |
        sudo apt-get install unzip
        curl -sS https://getcomposer.org/installer | php
        php composer.phar install

    - name: Run PHPUnit tests
      run: |
        ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests/AuthTest
